// src/lib/sources.ts
// AUTO-GENERATED — DO NOT EDIT MANUALLY
// Edit __CONFIG__.ts then run: npm run gen:sources

import { loader } from "fumadocs-core/source";
import { PROJECTS } from "__CONFIG__";

// v14: collections live in "collections/server" (tsconfig alias → .source/server)
// These named exports are generated by fumadocs-mdx when you run next dev/build
import {
  docsDocs,
  n0shopDocs,
} from ".source/server";

export const docsSource = loader({
  baseUrl: "/docs",
  // v14: .toFumadocsSource() replaces createMDXSource(docs, meta)
  source: docsDocs.toFumadocsSource(),
});

export const n0shopSource = loader({
  baseUrl: "/n0shop",
  // v14: .toFumadocsSource() replaces createMDXSource(docs, meta)
  source: n0shopDocs.toFumadocsSource(),
});

// Central dispatch registry consumed by app/[project]/layout.tsx + page.tsx
// ReturnType<typeof loader> is the correct type — loader() is not generic here
// eslint-disable-next-line @typescript-eslint/no-explicit-any
export const SOURCE_REGISTRY: Record<string, ReturnType<typeof loader<any>>> = {
  "docs": docsSource,
  "n0shop": n0shopSource,
};

// Derived from PROJECTS — used in layout for 404 guard
export const VALID_SLUGS = new Set(PROJECTS.map((p) => p.slug));